### ISSUE TITLE
Snapshot sent to PR

### ISSUE THREAD

**Issue by kyle4269** [ljmerza/frigate_plate_recognizer#10]
Hey @ljmerza 

Is it possible to use the identical snapshot stored in Frigate Events for PR to analyze? I've observed instances where the snapshot forwarded to PR has the plate cute off. The initial image depicts what was transmitted to PR, whereas the subsequent image, sourced from the events page, reveals the complete plate just a second later. I'm uncertain about the feasibility of this request, but I want to express appreciation for the exceptional work thus far. 

Thank you!

 
![1724_4ED6H_upload](https://github.com/ljmerza/frigate_plate_recognizer/assets/18011470/d453c539-9fa5-417f-9c55-69139ef0abcf)
![snapshot-1699982649 77124-4vv23v](https://github.com/ljmerza/frigate_plate_recognizer/assets/18011470/7e1e4090-3db4-4e93-b9b1-aa1581470ed8)

**Comment by ljmerza** [comment]
This was a long discussion in another issue because frigate will pump out many of the same events and you'll run out of free credits very fast. Since frigate is only looking for a vehicle and not necessarily a license plate, it's impossible to determine the best version for this extension. Frigate plus should have license plate objects at some point and will make this far more useful in the future. The agreement for now was youd find the highest scoring event and use that for license plate recognition

**Comment by kyle4269** [comment]
Great! Thank you for the response, I kind of figured it had something to do with the amount of images it would send to PR. I've had Frigate plus for some time now and seems to be working really well for me so far.

**Comment by bagobones** [comment]
> Since frigate is only looking for a vehicle and not necessarily a license plate,

The new frigate plus model in beta has a plate object specifically to address the issue.. I am not using the new custom models yet but probably should add a config option for only selecting plate events for the future.

In the meantime further fine tuning of the new zone filters / events with just cars might help as events fire on entering or leaving zones.. Maybe narrowing down to the ENTER or Exit event would help.

I am kind of confused how my car backing up to the street NEVER gets a good shot of my plate  when the frigate event clearly shows my car facing the camera DEAD ON when it hits the "driveway_entrance" zone when leaving.

**Comment by ljmerza** [comment]
v1.5.0 supports custom objects configuration. defaults to bus, motorzylce, and car

**Comment by kyle4269** [comment]
Looking through the json data, when the a license plate is detected. It shows up in attributes. 

```
"attributes": [
  {
    "box": [
      0.42552083333333335,
      0.8268518518518518,
      0.11041666666666666,
      0.14444444444444443
    ],
    "label": "license_plate",
    "score": 0.8046875
  }
],
```

**Comment by ljmerza** [comment]
thanks i dont have frigate plus so wasnt sure of the structure. added `frigate_plus` option in v1.6.0

**Comment by kyle4269** [comment]
Great! I'm gonna give it a try now and run a few tests

**Comment by kyle4269** [comment]
@ljmerza 
See the error below. I added frigate_plus: true to my config.

```
frigate_plate_test  | Traceback (most recent call last):
frigate_plate_test  |   File "//./index.py", line 309, in <module>
frigate_plate_test  |     main()
frigate_plate_test  |   File "//./index.py", line 305, in main
frigate_plate_test  |     run_mqtt_client()
frigate_plate_test  |   File "//./index.py", line 268, in run_mqtt_client
frigate_plate_test  |     mqtt_client.loop_forever()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
frigate_plate_test  |     rc = self._loop(timeout)
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
frigate_plate_test  |     rc = self.loop_read()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
frigate_plate_test  |     rc = self._packet_read()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
frigate_plate_test  |     rc = self._packet_handle()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
frigate_plate_test  |     return self._handle_publish()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
frigate_plate_test  |     self._handle_on_message(message)
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
frigate_plate_test  |     on_message(self, self._userdata, message)
frigate_plate_test  |   File "//./index.py", line 144, in on_message
frigate_plate_test  |     if not any(attribute['label'] == 'license_plate' for attribute in attributes):
frigate_plate_test  |   File "//./index.py", line 144, in <genexpr>
frigate_plate_test  |     if not any(attribute['label'] == 'license_plate' for attribute in attributes):
frigate_plate_test  | TypeError: string indices must be integers
frigate_plate_test exited with code 0
```

**Comment by kyle4269** [comment]
I was able to get it working with the way nick did it with CPAI. I'm no python expert so it's probably not pretty.. but...

```
    if(config['frigate'].get('frigate_plus', False)):
        #attributes = after_data.get('attributes', [])
        attributes = after_data['attributes']
        #if not any(attribute['label'] == 'license_plate' for attribute in attributes):
        if not attributes:
            _LOGGER.debug(f"no license_plate attribute found in event attributes")
            return
```

**Comment by ljmerza** [comment]
can you enable debug mode and show me the evbent when this error happens? the event strucutre may not be consistent

**Comment by kyle4269** [comment]
> File "//./index.py", line 144, in <genexpr>

```
frigate_plate_test  | 2023-11-16 13:43:33,021 - __main__ - DEBUG - mqtt message: {'before': {'id': '1700160212.678319-cbsela', 'camera': 'test', 'frame_time': 1700160212.884405, 'snapshot': {'frame_time': 1700160212.746444, 'box': [1332, 1, 1912, 355], 'area': 205320, 'region': [1264, 0, 1920, 656], 'score': 0.81640625, 'attributes': [{'label': 'license_plate', 'score': 0.82421875, 'box': [1619, 156, 1740, 214]}]}, 'label': 'car', 'sub_label': None, 'top_score': 0.826171875, 'false_positive': False, 'start_time': 1700160212.678319, 'end_time': None, 'score': 0.89453125, 'box': [1306, 1, 1906, 383], 'area': 229200, 'ratio': 1.5706806282722514, 'region': [1220, 0, 1920, 700], 'stationary': False, 'motionless_count': 2, 'position_changes': 1, 'current_zones': [], 'entered_zones': [], 'has_clip': False, 'has_snapshot': False, 'attributes': {'license_plate': 0.82421875}, 'current_attributes': [{'label': 'license_plate', 'score': 0.75390625, 'box': [1592, 175, 1709, 235]}]}, 'after': {'id': '1700160212.678319-cbsela', 'camera': 'test', 'frame_time': 1700160212.94422, 'snapshot': {'frame_time': 1700160212.746444, 'box': [1332, 1, 1912, 355], 'area': 205320, 'region': [1264, 0, 1920, 656], 'score': 0.81640625, 'attributes': [{'label': 'license_plate', 'score': 0.82421875, 'box': [1619, 156, 1740, 214]}]}, 'label': 'car', 'sub_label': None, 'top_score': 0.8359375, 'false_positive': False, 'start_time': 1700160212.678319, 'end_time': None, 'score': 0.890625, 'box': [1278, 1, 1904, 389], 'area': 242888, 'ratio': 1.6134020618556701, 'region': [1200, 0, 1920, 720], 'stationary': False, 'motionless_count': 3, 'position_changes': 1, 'current_zones': ['Lp'], 'entered_zones': ['Lp'], 'has_clip': True, 'has_snapshot': True, 'attributes': {'license_plate': 0.82421875}, 'current_attributes': [{'label': 'license_plate', 'score': 0.67578125, 'box': [1574, 185, 1686, 243]}]}, 'type': 'update'}
frigate_plate_test  | Traceback (most recent call last):
frigate_plate_test  |   File "//./index.py", line 309, in <module>
frigate_plate_test  |     main()
frigate_plate_test  |   File "//./index.py", line 305, in main
frigate_plate_test  |     run_mqtt_client()
frigate_plate_test  |   File "//./index.py", line 268, in run_mqtt_client
frigate_plate_test  |     mqtt_client.loop_forever()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
frigate_plate_test  |     rc = self._loop(timeout)
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
frigate_plate_test  |     rc = self.loop_read()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
frigate_plate_test  |     rc = self._packet_read()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
frigate_plate_test  |     rc = self._packet_handle()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
frigate_plate_test  |     return self._handle_publish()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
frigate_plate_test  |     self._handle_on_message(message)
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
frigate_plate_test  |     on_message(self, self._userdata, message)
frigate_plate_test  |   File "//./index.py", line 144, in on_message
frigate_plate_test  |     if not any(attribute['label'] == 'license_plate' for attribute in attributes):
frigate_plate_test  |   File "//./index.py", line 144, in <genexpr>
frigate_plate_test  |     if not any(attribute['label'] == 'license_plate' for attribute in attributes):
frigate_plate_test  | TypeError: string indices must be integers
frigate_plate_test exited with code 0

```

**Comment by ljmerza** [comment]
the event should ahve printed out

**Comment by kyle4269** [comment]
> the event should have printed out thats what i need to bee
sorry. It seems to be skipping it..

```
2023-11-16 16:34:25,960 - __main__ - DEBUG - mqtt message: {'before': {'id': '1700170460.148672-p600mw', 'camera': 'test', 'frame_time': 1700170465.818042, 'snapshot': {'frame_time': 1700170463.415216, 'box': [700, 7, 1770, 622], 'area': 658050, 'region': [584, 0, 1920, 1336], 'score': 0.9140625, 'attributes': [{'label': 'license_plate', 'score': 0.6953125, 'box': [1405, 419, 1470, 466]}]}, 'label': 'car', 'sub_label': None, 'top_score': 0.978515625, 'false_positive': False, 'start_time': 1700170460.148672, 'end_time': None, 'score': 0.94921875, 'box': [203, 9, 1685, 1015], 'area': 1490892, 'ratio': 1.4731610337972167, 'region': [65, 0, 1833, 1768], 'stationary': False, 'motionless_count': 12, 'position_changes': 1, 'current_zones': [], 'entered_zones': ['Lp'], 'has_clip': True, 'has_snapshot': True, 'attributes': {'license_plate': 0.6953125}, 'current_attributes': [{'label': 'license_plate', 'score': 0.62890625, 'box': [1078, 746, 1131, 786]}]}, 'after': {'id': '1700170460.148672-p600mw', 'camera': 'test', 'frame_time': 1700170465.878349, 'snapshot': {'frame_time': 1700170463.415216, 'box': [700, 7, 1770, 622], 'area': 658050, 'region': [584, 0, 1920, 1336], 'score': 0.9140625, 'attributes': [{'label': 'license_plate', 'score': 0.6953125, 'box': [1405, 419, 1470, 466]}]}, 'label': 'car', 'sub_label': None, 'top_score': 0.978515625, 'false_positive': False, 'start_time': 1700170460.148672, 'end_time': None, 'score': 0.96484375, 'box': [184, 7, 1669, 988], 'area': 1456785, 'ratio': 1.5137614678899083, 'region': [54, 0, 1826, 1772], 'stationary': False, 'motionless_count': 13, 'position_changes': 1, 'current_zones': [], 'entered_zones': ['Lp'], 'has_clip': True, 'has_snapshot': True, 'attributes': {'license_plate': 0.6953125}, 'current_attributes': []}, 'type': 'update'}
2023-11-16 16:34:25,960 - __main__ - DEBUG - Skipping event: 1700170460.148672-p600mw because it does not match the configured zones/cameras
```

```
frigate:
  frigate_url: http://****:5000
  mqtt_server: *****
  mqtt_auth: true
  mqtt_username: mqtt
  mqtt_password: ******
  main_topic: frigate
  return_topic: plate_recognizer
  frigate_plus: true
  camera:
    - test
  zones:
    - Lp
  objects:
    - car
  min_score: .65
plate_recognizer:
  token: ******
  regions:
    - us-ri
logger_level: DEBUG

```

**Comment by ljmerza** [comment]
okay try v1.6.1 that should clear it up. i also added an optional `license_plate_min_score`

**Comment by kyle4269** [comment]
Success! Works perfect! Thank you for the work you do
