### ISSUE TITLE
1.8.11 errors

### ISSUE THREAD

**Issue by DrSpaldo** [ljmerza/frigate_plate_recognizer#35]
I have started getting a few errors since updating, it isn't working anymore. Any ideas?

```
2024-02-12 17:37:14,192 - __main__ - INFO - Time: 2024-02-12 17:37:14.192
2024-02-12 17:37:14,192 - __main__ - INFO - Python Version: 3.9.18 (main, Feb 1 2024, 05:56:53)

[GCC 12.2.0]
2024-02-12 17:37:14,192 - __main__ - INFO - Frigate Plate Recognizer Version: 1.8.11

2024-02-12 17:37:14,192 - __main__ - INFO - Using CodeProject.AI API
2024-02-12 17:37:14,192 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.2.20
2024-02-12 17:37:14,193 - __main__ - INFO - MQTT Connected
2024-02-12 17:37:21,752 - __main__ - INFO - Saving image with path: /plates/street3_2024-02-12_17-37.png
2024-02-12 17:39:22,056 - __main__ - INFO - Saving image with path: /plates/street3_2024-02-12_17-39.png
Traceback (most recent call last):
File "/usr/src/app/./index.py", line 583, in <module>
main()
File "/usr/src/app/./index.py", line 579, in main
run_mqtt_client()
File "/usr/src/app/./index.py", line 538, in run_mqtt_client
mqtt_client.loop_forever()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
rc = self._loop(timeout)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
rc = self.loop_read()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
rc = self._packet_read()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
rc = self._packet_handle()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
return self._handle_publish()
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
self._handle_on_message(message)
File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
on_message(self, self._userdata, message)
File "/usr/src/app/./index.py", line 472, in on_message
plate_number, plate_score, watched_plate, fuzzy_score = get_plate(snapshot)
File "/usr/src/app/./index.py", line 399, in get_plate
plate_number, plate_score, watched_plate, fuzzy_score = code_project(snapshot)
File "/usr/src/app/./index.py", line 101, in code_project
watched_plate, watched_score, fuzzy_score = check_watched_plates(plate_number, response['predictions'])
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by danielszilagyi** [comment]
Check https://github.com/ljmerza/frigate_plate_recognizer/issues/34 for a quick fix

**Comment by danielszilagyi** [comment]
I changed the mentioned line in `index.py` and the issue was solved. adding a watched plate into the config file probably also fixes this.

**Comment by danielszilagyi** [comment]
You can use docker cp to copy out a file from container, edit it locally and copy back into the container

**Comment by DrSpaldo** [comment]
I worked out another way to find the file, thanks. It seems to be working now :)

**Comment by ljmerza** [comment]
dup https://github.com/ljmerza/frigate_plate_recognizer/issues/34
