### ISSUE TITLE
Crashing when it has a snapshot and says 'no connection adaprers were found'

### ISSUE THREAD

**Issue by rhamblen** [ljmerza/frigate_plate_recognizer#37]
MQTTis on 192.168.1.60 and we connect there.
FrigatePlateRecognizer is on 192.168.1.66, if I go to the link, there is a snap there.  so it is something about the setup, but I cant see what.

Any pointers?

Thanks

```
2024-02-16 13:00:29,764 - __main__ - INFO - Time: 2024-02-16 13:00:29.764
2024-02-16 13:00:29,764 - __main__ - INFO - Python Version: 3.9.18 (main, Feb 13 2024, 10:54:04) 
[GCC 12.2.0]
2024-02-16 13:00:29,764 - __main__ - INFO - Frigate Plate Recognizer Version: 1.8.13
2024-02-16 13:00:29,764 - __main__ - INFO - Using Plate Recognizer API
2024-02-16 13:00:29,764 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.1.60
2024-02-16 13:00:29,765 - __main__ - INFO - MQTT Connected
Traceback (most recent call last):
  File "/usr/src/app/./index.py", line 581, in <module>
    main()
  File "/usr/src/app/./index.py", line 577, in main
    run_mqtt_client()
  File "/usr/src/app/./index.py", line 536, in run_mqtt_client
    mqtt_client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/src/app/./index.py", line 458, in on_message
    snapshot = get_snapshot(frigate_event_id, frigate_url, True)
  File "/usr/src/app/./index.py", line 324, in get_snapshot
    response = requests.get(snapshot_url, params={ "crop": cropped, "quality": 95 })
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
  **File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '192.168.1.66:5000/api/events/1708085626.97561-nw55x6/snapshot.jpg'**
```

**Comment by ljmerza** [comment]
you need the http part in your config

**Comment by rhamblen** [comment]
coinfirm that fixed things.
