### ISSUE TITLE
container crashing upon 404 of camera?

### ISSUE THREAD

**Issue by atv2016** [ljmerza/frigate_plate_recognizer#42]
```
rigate_plate_recognizer    | 2024-02-26 11:02:06,545 - __main__ - ERROR - Error getting snapshot: 404
frigate_plate_recognizer    | Traceback (most recent call last):
frigate_plate_recognizer    |   File "/usr/src/app/./index.py", line 581, in <module>
frigate_plate_recognizer    |     main()
frigate_plate_recognizer    |   File "/usr/src/app/./index.py", line 577, in main
frigate_plate_recognizer    |     run_mqtt_client()
frigate_plate_recognizer    |   File "/usr/src/app/./index.py", line 536, in run_mqtt_client
frigate_plate_recognizer    |     mqtt_client.loop_forever()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
frigate_plate_recognizer    |     rc = self._loop(timeout)
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
frigate_plate_recognizer    |     rc = self.loop_read()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
frigate_plate_recognizer    |     rc = self._packet_read()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
frigate_plate_recognizer    |     rc = self._packet_handle()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
frigate_plate_recognizer    |     return self._handle_publish()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
frigate_plate_recognizer    |     self._handle_on_message(message)
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
frigate_plate_recognizer    |     on_message(self, self._userdata, message)
frigate_plate_recognizer    |   File "/usr/src/app/./index.py", line 460, in on_message
frigate_plate_recognizer    |     del CURRENT_EVENTS[frigate_event_id] # remove existing id from current events due to snapshot failure - will try again next frame
frigate_plate_recognizer    | KeyError: '1708945317.031828-3gm5m8'
```

**Comment by kyle4269** [comment]
@ljmerza & @gadget-man I don't have the time to try this, but I think this would solve the issue where the event ID doesn't exist and crashes.

```
if not snapshot:
    # Check if the key exists in the dictionary before attempting to delete
    if frigate_event_id in CURRENT_EVENTS:
        del CURRENT_EVENTS[frigate_event_id]
    else:
        _LOGGER.debug(f"Key {frigate_event_id} not found in CURRENT_EVENTS.") 
    return
```

**Comment by ljmerza** [comment]
added check in v1.8.14
