### ISSUE TITLE
Limit detection to specific zones

### ISSUE THREAD

**Issue by yehpo** [ljmerza/frigate_plate_recognizer#5]
It would also be nice if we can limit the process to specific zones, not only cameras, that way we can skip the detection for zones where the plate wouldn't be visible.

_Originally posted by @yehpo in https://github.com/ljmerza/frigate_plate_recognizer/issues/2#issuecomment-1725392283_

**Comment by bagobones** [comment]
Just fired this up and I have 66 api calls already and technically there should be none as NO valid snapshot or clip event has happened on the selected camera. I am going to uninstall it as I think it is firing on ALL mqtt events like in debug view, i will likely run out of API calls  before end of day .

**Comment by regnighc** [comment]
The same thing is happening to me, I have zones configured as per frigate documentation to avoid stationary parked cars from triggering but hundreds of images are being sent to the platerecognizer api. None of the false events are being recorded or snapshot in Frigate, only the platerecognizer api. I cannot see any other way that I can prevent these api called. Its even sending motion from the street which is completely masked out and not in the recording zone.

**Comment by ljmerza** [comment]
added to v1.4.0 check the docs

**Comment by bagobones** [comment]
Not sure if the new "zones" looks like this is just causing a crashing / reboot loop on events.

```
frigate:
  frigate_url: http://xxxxxxxxxx:5000
  mqtt_server: xxxxxxxxxxxx
  mqtt_auth: true
  mqtt_username: xxxxx
  mqtt_password: xxxxxxxxxxxxxxx
  main_topic: frigate
  return_topic: plate_recognizer
  camera:
    - driveway_cam
  zones:
    - driveway_entrance
  min_score: .8
plate_recognizer:
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  regions: 
    - us-ca
logger_level: INFO
```


```
2023-11-14 10:15:54,917 - __main__ - INFO - Frigate Plate Recognizer Version: 1.4.0
2023-11-14 10:15:54,917 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.102.20
2023-11-14 10:15:54,919 - __main__ - INFO - MQTT Connected
Traceback (most recent call last):
  File "//./index.py", line 301, in <module>
    main()
  File "//./index.py", line 297, in main
    run_mqtt_client()
  File "//./index.py", line 260, in run_mqtt_client
    mqtt_client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "//./index.py", line 126, in on_message
    matching_zone = any(value in after_data['zones'] for value in config_zones)
  File "//./index.py", line 126, in <genexpr>
    matching_zone = any(value in after_data['zones'] for value in config_zones)
KeyError: 'zones'
2023-11-14 10:16:33,618 - __main__ - INFO - Time: 2023-11-14 10:16:33.618
2023-11-14 10:16:33,618 - __main__ - INFO - Python Version: 3.9.18 (main, Nov  1 2023, 14:29:07) 

[GCC 12.2.0]
2023-11-14 10:16:33,618 - __main__ - INFO - Frigate Plate Recognizer Version: 1.4.0
2023-11-14 10:16:33,618 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.102.20
2023-11-14 10:16:33,620 - __main__ - INFO - MQTT Connected
Traceback (most recent call last):
  File "//./index.py", line 301, in <module>
    main()
  File "//./index.py", line 297, in main
    run_mqtt_client()
  File "//./index.py", line 260, in run_mqtt_client
    mqtt_client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "//./index.py", line 126, in on_message
    matching_zone = any(value in after_data['zones'] for value in config_zones)
  File "//./index.py", line 126, in <genexpr>
    matching_zone = any(value in after_data['zones'] for value in config_zones)
KeyError: 'zones'
2023-11-14 10:17:00,206 - __main__ - INFO - Time: 2023-11-14 10:17:00.206
2023-11-14 10:17:00,206 - __main__ - INFO - Python Version: 3.9.18 (main, Nov  1 2023, 14:29:07) 

[GCC 12.2.0]
2023-11-14 10:17:00,207 - __main__ - INFO - Frigate Plate Recognizer Version: 1.4.0
2023-11-14 10:17:00,207 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.102.20
2023-11-14 10:17:00,208 - __main__ - INFO - MQTT Connected
Traceback (most recent call last):
  File "//./index.py", line 301, in <module>
    main()
  File "//./index.py", line 297, in main
    run_mqtt_client()
  File "//./index.py", line 260, in run_mqtt_client
    mqtt_client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "//./index.py", line 126, in on_message
    matching_zone = any(value in after_data['zones'] for value in config_zones)
  File "//./index.py", line 126, in <genexpr>
    matching_zone = any(value in after_data['zones'] for value in config_zones)
KeyError: 'zones'
```

**Comment by regnighc** [comment]
I started using zones too today but I've not experienced the same issues, however I did notice that most of my car detections are not being tagged with the plate number anymore, the same detections do get a plate detection on the API though so its just not getting back to Frigate for some reason. Not sure if its related to the change.

**Comment by bagobones** [comment]
Did some more testing, with the zone config above or only the zone config and no camera it just seems to crash on every event.

Disabling it as unusable still .

**Comment by kyle4269** [comment]
He's fixed the issue with the zones
