### ISSUE TITLE
connected ok but errors, unsure why

### ISSUE THREAD

**Issue by trendstyle** [ljmerza/frigate_plate_recognizer#54]
frigate_plate_recognizer  | 2024-03-29 11:28:30,911 - __main__ - INFO - MQTT Connected
frigate_plate_recognizer  | Traceback (most recent call last):
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
frigate_plate_recognizer  |     return complexjson.loads(self.text, **kwargs)
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
frigate_plate_recognizer  |     return _default_decoder.decode(s)
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
frigate_plate_recognizer  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
frigate_plate_recognizer  |     raise JSONDecodeError("Expecting value", s, err.value) from None
frigate_plate_recognizer  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
frigate_plate_recognizer  | 
frigate_plate_recognizer  | During handling of the above exception, another exception occurred:
frigate_plate_recognizer  | 
frigate_plate_recognizer  | Traceback (most recent call last):
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 583, in <module>
frigate_plate_recognizer  |     main()
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 579, in main
frigate_plate_recognizer  |     run_mqtt_client()
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 538, in run_mqtt_client
frigate_plate_recognizer  |     mqtt_client.loop_forever()
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
frigate_plate_recognizer  |     rc = self._loop(timeout)
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
frigate_plate_recognizer  |     rc = self.loop_read()
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
frigate_plate_recognizer  |     rc = self._packet_read()
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
frigate_plate_recognizer  |     rc = self._packet_handle()
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
frigate_plate_recognizer  |     return self._handle_publish()
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
frigate_plate_recognizer  |     self._handle_on_message(message)
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
frigate_plate_recognizer  |     on_message(self, self._userdata, message)
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 472, in on_message
frigate_plate_recognizer  |     plate_number, plate_score, watched_plate, fuzzy_score = get_plate(snapshot)
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 397, in get_plate
frigate_plate_recognizer  |     plate_number, plate_score, watched_plate, fuzzy_score = code_project(snapshot)
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 87, in code_project
frigate_plate_recognizer  |     response = response.json()
frigate_plate_recognizer  |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
frigate_plate_recognizer  |     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
frigate_plate_recognizer  | requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ljmerza** [comment]
can you add debugging?
