### ISSUE TITLE
API call fails

### ISSUE THREAD

**Issue by tuckshoprn** [ljmerza/frigate_plate_recognizer#69]
Version 2.1.1
Frigate version 0.14.1-f4f3cfa

Plate recognizer keeps rebooting with the following error:
`Traceback (most recent call last):
  File "/usr/src/app/./index.py", line 445, in <module>
    main()
  File "/usr/src/app/./index.py", line 441, in main
    run_mqtt_client()
  File "/usr/src/app/./index.py", line 388, in run_mqtt_client
    mqtt_client = mqtt.Client("ALPR_maindrive" + current_time)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 772, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details’

**Comment by tuckshoprn** [comment]
changing this section in index.py solves the issue temporarily until v2.0 is implemented.

`def run_mqtt_client():
    global mqtt_client
    _LOGGER.info(f"Starting MQTT client. Connecting to: {config['frigate']['mqtt_server']}")
    now = datetime.now()
    current_time = now.strftime("%Y%m%d%H%M%S")

    # setup mqtt client
    mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1,"ALPR_maindrive" + current_time)
    mqtt_client.on_message = on_message
    mqtt_client.on_disconnect = on_disconnect
    mqtt_client.on_connect = on_connect

    # check if we are using authentication and set username/password if so
    if config['frigate']['mqtt_auth']:
        username = config['frigate']['mqtt_username']
        password = config['frigate']['mqtt_password']
        mqtt_client.username_pw_set(username, password)

    mqtt_client.connect(config['frigate']['mqtt_server'])
    mqtt_client.loop_forever()`
