### ISSUE TITLE
Mosquitto unexpected disconnection, trying to reconnect

### ISSUE THREAD

**Issue by mjc-506** [ljmerza/frigate_plate_recognizer#7]
Evening!

Having issues not connecting to a mosquitto broker (Eclipse mosquitto, also running as a Docker container)

```
[matt@homeserver ~]$ docker run -v /home/matt/frigateplate:/config -e TZ=Europe/London -it --name frigate_plate_recognizer lmerza/frigate_plate_recognizer:latest
2023-10-05 21:15:48,551 - __main__ - INFO - Time: 2023-10-05 21:15:48.551
2023-10-05 21:15:48,552 - __main__ - INFO - Python Version: 3.9.18 (main, Sep 20 2023, 11:31:57) 
[GCC 12.2.0]
2023-10-05 21:15:48,552 - __main__ - INFO - Frigate Plate Recognizer Version: 1.3.4
2023-10-05 21:15:48,552 - __main__ - INFO - Starting MQTT client. Connecting to: 172.17.0.4
2023-10-05 21:15:48,553 - __main__ - INFO - MQTT Connected
2023-10-05 21:15:48,554 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
2023-10-05 21:15:49,556 - __main__ - INFO - MQTT Connected
2023-10-05 21:15:49,556 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
2023-10-05 21:15:51,557 - __main__ - INFO - MQTT Connected
2023-10-05 21:15:51,557 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
2023-10-05 21:15:55,559 - __main__ - INFO - MQTT Connected
2023-10-05 21:15:55,559 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
2023-10-05 21:16:03,560 - __main__ - INFO - MQTT Connected
2023-10-05 21:16:03,560 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
2023-10-05 21:16:19,562 - __main__ - INFO - MQTT Connected
2023-10-05 21:16:19,562 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
2023-10-05 21:16:51,565 - __main__ - INFO - MQTT Connected
2023-10-05 21:16:51,565 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
2023-10-05 21:17:55,567 - __main__ - INFO - MQTT Connected
2023-10-05 21:17:55,567 - __main__ - WARNING - Unexpected disconnection, trying to reconnect
```

config.yml contains:
```
frigate:
  frigate_url: http://127.0.0.1:5000
  mqtt_server: 172.17.0.4
  mqtt_auth: true
  mqtt_username: <user>
  mqtt_password: <pass>
  main_topic: frigate
  return_topic: plate_recognizer
  camera:
    - front
  min_score: .8
plate_recognizer:
  api_url: http://127.0.0.1:8080/v1/plate-reader
  token: 9b8fc6cd2e06e7eee8ca021ff88f42c206726f3d
  regions:
    - gb
logger_level: INFO
```

mqtt_server is the Docker ip, if I use the host ip the container fails to start with:

```
2023-10-05 21:23:59,426 - __main__ - INFO - Time: 2023-10-05 21:23:59.426
2023-10-05 21:23:59,426 - __main__ - INFO - Python Version: 3.9.18 (main, Sep 20 2023, 11:31:57) 
[GCC 12.2.0]
2023-10-05 21:23:59,426 - __main__ - INFO - Frigate Plate Recognizer Version: 1.3.4
2023-10-05 21:23:59,426 - __main__ - INFO - Starting MQTT client. Connecting to: 127.0.0.1
Traceback (most recent call last):
  File "//./index.py", line 290, in <module>
    main()
  File "//./index.py", line 286, in main
    run_mqtt_client()
  File "//./index.py", line 248, in run_mqtt_client
    mqtt_client.connect(config['frigate']['mqtt_server'])
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

The MQTT broker is listening on 1883 (mqtt) but 9001 (websocket) is mapped to 9003, could this be an issue? Is there a 'port' config?

**Comment by stephengolub** [comment]
I'm having the same issue, and figured out it was definitely the port. The `mqtt` python library used doesn't have the capability to parse the port from the server address setting.

I submitted a PR (#52) to add this ability.

**Comment by ljmerza** [comment]
PR was merged so should be fixed
